services:
# Node App
- type: web
  name: platformkit-auth
  env: node  
  region: oregon 
  plan: starter 
  numInstances: 1
  buildCommand: npm run preinstall; npm run prebuild;
  startCommand: npm run start
  envVars:
  - key: REPO
    sync: false
  - key: UI_DIRECTORY
    sync: false
  - key: BUILD_COMMAND
    sync: false
  - key: DATABASE_URL
    fromDatabase:
      name: pkauthdb
      property: connectionString  
  - key: JWT_SECRET    
    sync: false
  autoDeploy: false 

databases:
  - name: pkauthdb
    databaseName: pkauthdb      # optional (Render may add a suffix)
    user: pkauthdbuser            # optional    